export const demoJobs = [
  { id: 1, title: "Nhân viên Kinh doanh", company: "Công ty Cổ phần ABC", salary: "10 - 15 triệu", location: "Cầu Giấy, Hà Nội", date: "15/07/2026", status: "Đang hiển thị", applicants: 18 },
  { id: 2, title: "Lập trình viên Java", company: "Công ty Công nghệ XYZ", salary: "20 - 30 triệu", location: "Nam Từ Liêm, Hà Nội", date: "10/07/2026", status: "Chờ duyệt", applicants: 12 },
  { id: 3, title: "Kế toán tổng hợp", company: "Công ty Thương mại MNO", salary: "12 - 18 triệu", location: "Đống Đa, Hà Nội", date: "05/07/2026", status: "Đã đóng", applicants: 9 },
];

export const demoApplicants = [
  { id: 1, name: "Nguyễn Văn A", job: "Lập trình viên Java", date: "18/07/2026", status: "Đợi đọc", email: "nguyenvana@email.com", phone: "0987 654 321", birthDate: "15/08/2002", gender: "Nam", address: "Cầu Giấy, Hà Nội", desiredSalary: "20 - 25 triệu", desiredLocation: "Hà Nội", education: "Đại học Mở Hà Nội · Công nghệ thông tin · 2020 - 2024", experience: [{ company: "Công ty Công nghệ Hà Nội", position: "Java Developer", time: "06/2024 - Hiện tại", description: "Phát triển REST API bằng Spring Boot, tối ưu truy vấn SQL và phối hợp kiểm thử sản phẩm." }], skills: ["Java", "Spring Boot", "SQL", "React", "Git"], cvFile: "CV_Nguyen_Van_A.pdf" },
  { id: 2, name: "Trần Thị B", job: "Lập trình viên Java", date: "19/07/2026", status: "Phỏng vấn", email: "tranthib@email.com", phone: "0912 345 678", birthDate: "22/03/2001", gender: "Nữ", address: "Nam Từ Liêm, Hà Nội", desiredSalary: "22 - 28 triệu", desiredLocation: "Hà Nội", education: "Đại học Công nghiệp Hà Nội · Kỹ thuật phần mềm · 2019 - 2023", experience: [{ company: "Công ty Phần mềm Sao Việt", position: "Backend Developer", time: "08/2023 - Hiện tại", description: "Xây dựng dịch vụ Java, viết tài liệu API và tham gia triển khai hệ thống nội bộ." }], skills: ["Java", "Spring MVC", "PostgreSQL", "Docker", "Git"], cvFile: "CV_Tran_Thi_B.pdf" },
  { id: 3, name: "Lê Minh C", job: "Nhân viên Kinh doanh", date: "20/07/2026", status: "Đã duyệt", email: "leminhc@email.com", phone: "0966 123 456", birthDate: "09/11/2000", gender: "Nam", address: "Thanh Xuân, Hà Nội", desiredSalary: "12 - 18 triệu", desiredLocation: "Hà Nội", education: "Đại học Thương mại · Quản trị kinh doanh · 2018 - 2022", experience: [{ company: "Công ty Thương mại Việt Thành", position: "Nhân viên kinh doanh", time: "07/2022 - 06/2026", description: "Tìm kiếm khách hàng doanh nghiệp, tư vấn dịch vụ và chăm sóc khách hàng sau bán." }], skills: ["Bán hàng B2B", "Đàm phán", "CRM", "Thuyết trình", "Excel"], cvFile: "CV_Le_Minh_C.pdf" },
];
